# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171016_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook_url',
            field=models.CharField(blank=True, default='https://www.facebook.com', max_length=100, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='favourite_quote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='github_url',
            field=models.CharField(blank=True, default='https://www.github.com', max_length=100, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram_url',
            field=models.CharField(blank=True, default='https://www.instagram.com', max_length=100, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter_url',
            field=models.CharField(blank=True, default='https://www.twitter.com', max_length=100, verbose_name='Twitter URL'),
        ),
    ]
