# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('main_image', models.ImageField(upload_to='blogs')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_blogpost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blogpost',
                'ordering': ('-created_on',),
                'verbose_name_plural': 'Blogposts',
            },
        ),
    ]
